### ISSUE TITLE
ip:port

### ISSUE THREAD

**Issue by skydrome** [shuLhan/rescached-legacy#1]
When I specify a port after the ip in the form:
    server.parent=127.0.0.1:453
rescached fails to start.

using ArchLinux x86

**Comment by shuLhan** [comment]
Sorry for the delay.

This issue has been fixed in the new release.The problem is in libvos, Resolver module. You can view the changes log in libvos latest commit [1].

Thanks for the report and please inform me again if this issue is still exist or has been resolved.

[1] https://github.com/shuLhan/libvos/commit/1c62f114081e1608063960e7c2c063243b47c37f
