### ISSUE TITLE
Allow defining of CNAME entries

### ISSUE THREAD

**Issue by chadberg** [shuLhan/rescached-legacy#10]
Currently rescached will read A records from /etc/hosts and /etc/rescached/hosts.d/ but it would be great to also define CNAME style aliases. For example, it would be great if I could define an entry pointing 'my.home' to 'my.dyn.dns' rather than having to kludge a way of updating the listed IP address in a hosts file all the time.

**Comment by shuLhan** [comment]
Hello @chadberg ,

Just for information, this repository is now deprecated.  We have been migrate the rescached implementation to Go.  Your issue is resolved in new implementation using master file format [1].

Thank you again for reporting this issue and for using this software.

[1] https://github.com/shuLhan/rescached-go/#master-file
